name: Idee oder Wunsch
description: Vorschlag für eine neue Funktion oder ein neues Thema.
title: 'Idee: '
labels: [idee]
body:
  - type: textarea
    id: idee
    attributes:
      label: Worum geht es?
    validations:
      required: true
  - type: textarea
    id: nutzen
    attributes:
      label: Was wird dadurch beim Lernen besser?
